export const FETCH_WEEKDAY_JOBS_REQUEST = 'FETCH_WEEKDAY_JOBS_REQUEST';
export const FETCH_WEEKDAY_JOBS_SUCCESS = 'FETCH_WEEKDAY_JOBS_SUCCESS';
export const FETCH_WEEKDAY_JOBS_FAILURE = 'FETCH_WEEKDAY_JOBS_FAILURE';
export const SET_FILTERS = 'SET_FILTERS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';